os:
  - linux
sudo: true
addons:
  apt:
    packages:
      - snapd
install:
  - sudo snap install flutter --classic
before_script:
  - flutter doctor
  - flutter pub get
script:
  - flutter test
  - flutter build web --web-renderer html --release
deploy:
  provider: pages
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: build/web
  on:
    branch: main