name: catalyst
description: Estudos organizados e eficientes, de forma totalmente gratuita.

publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 4.0.2

flutter:
  assets:
    - resources/
    - resources/locale/
    - resources/courses/
    - resources/courses/enem/
  uses-material-design: true
